name: fpl-go

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - name: Run go mod tidy
      run: go mod tidy
    
    - name: Build
      run: go build -v ./...

    - name: Run gofmt
      run: gofmt -w -l -s ./

    - name: Run tests
      run: go test -v ./...
